# Generated by Django 4.2.10 on 2025-04-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
