# Generated by Django 4.2.16 on 2025-09-14 14:47

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Receta', '0002_receta_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dash', '0001_initial'),
        ('Productos', '0012_alter_producto_imagen'),
        ('Cierre', '0002_alter_cierre_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuadreReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_empanizado', models.DateField(blank=True, null=True)),
                ('fecha_gas', models.DateField(blank=True, null=True)),
                ('fecha_cambio_aceite', models.DateField(blank=True, null=True)),
                ('venta_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gasto_diario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('efectivo_caja', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_depositar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('numero_boleta', models.CharField(blank=True, max_length=100, null=True)),
                ('total_pollo_rey', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('numero_factura_pollo', models.CharField(blank=True, max_length=100, null=True)),
                ('libras_pollo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('otros', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dash.tienda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', 'tienda'],
                'unique_together': {('fecha', 'tienda')},
            },
        ),
        migrations.CreateModel(
            name='DetalleCuadreInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'Producto'), ('R', 'Receta')], max_length=1)),
                ('stock_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ingreso', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('stock_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cuadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_inventario', to='Cierre.cuadrereporte')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Productos.producto')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Receta.receta')),
            ],
            options={
                'unique_together': {('cuadre', 'receta'), ('cuadre', 'producto')},
            },
        ),
    ]
