# Generated by Django 4.2.16 on 2025-09-15 16:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cierre', '0003_cuadrereporte_detallecuadreinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadrereporte',
            name='faltante',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
