# Generated by Django 5.1.5 on 2025-11-18 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentaTienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('encargada', models.CharField(max_length=100)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gasto_diario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_depositar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pollo_rey', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('no_boleta', models.CharField(blank=True, max_length=50, null=True)),
                ('libras_pollo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('factura', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='VentaTienda.registrodia')),
            ],
        ),
        migrations.CreateModel(
            name='ControlProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentaTienda.producto')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='VentaTienda.registrodia')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentaTienda.producto')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='VentaTienda.registrodia')),
            ],
        ),
    ]
