# Generated by Django 5.2.3 on 2025-11-19 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0001_initial'),
        ('VentaTienda', '0002_producto_registrodia_gasto_controlproducto_venta'),
    ]

    operations = [
        # Solo crear el nuevo modelo, no intentar eliminar los viejos que no existen en BD
        migrations.CreateModel(
            name='ControlDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('productos_saldos', models.JSONField(blank=True, default=dict)),
                ('venta_productos', models.JSONField(blank=True, default=dict)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_diario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('efectivo_caja', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_depositar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('no_boleta', models.CharField(blank=True, max_length=100, null=True)),
                ('total_pollo_rey', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('no_factura_pollo_rey', models.CharField(blank=True, max_length=100, null=True)),
                ('libras_pollo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_facturacion', models.CharField(blank=True, max_length=100, null=True)),
                ('gastos', models.JSONField(blank=True, default=list)),
                ('fechas_control', models.JSONField(blank=True, default=dict)),
                ('otros', models.TextField(blank=True, null=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dash.tienda')),
                ('usuario_tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentaTienda.usuariotienda')),
            ],
            options={
                'verbose_name': 'Control Diario',
                'verbose_name_plural': 'Controles Diarios',
                'ordering': ['-fecha'],
                'unique_together': {('tienda', 'fecha')},
            },
        ),
    ]
