# Generated by Django 4.2.16 on 2025-11-25 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VentaTienda', '0003_remove_gasto_registro_remove_venta_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='registro',
        ),
        migrations.DeleteModel(
            name='ControlProducto',
        ),
        migrations.DeleteModel(
            name='Gasto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='RegistroDia',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
