# Generated by Django 4.2.16 on 2025-05-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_rename_fecha_mod_producto_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_modificacion',
            new_name='fecha_mod',
        ),
    ]
