# Generated by Django 4.2.16 on 2025-05-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_rename_fecha_creacion_producto_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_mod',
            new_name='fecha_modificacion',
        ),
    ]
