# Generated by Django 4.2.16 on 2025-06-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_rename_fecha_producto_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ingreso',
            field=models.IntegerField(default=0),
        ),
    ]
