# Generated by Django 4.2.16 on 2025-06-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_remove_producto_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ingreso',
            field=models.IntegerField(default=0),
        ),
    ]
