# Generated by Django 4.2.16 on 2025-06-10 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0009_producto_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ingreso',
        ),
    ]
