# Generated by Django 4.2.16 on 2025-10-28 22:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Categoria', '0003_categoria_imagen'),
        ('Productos', '0012_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoproducto',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date(2025, 10, 27)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Categoria.categoria'),
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha', models.CharField(max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.insumos'),
        ),
    ]
