# Generated by Django 4.2.16 on 2025-11-16 21:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0001_initial'),
        ('Productos', '0013_ingresoproducto_fecha_ingreso_alter_producto_id_cate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='insumos',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Dash.tienda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingresoproducto',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date(2025, 11, 15)),
        ),
    ]
