# Generated by Django 4.2.16 on 2025-11-25 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0014_insumos_precio_compra_insumos_tienda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoproducto',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date(2025, 11, 24)),
        ),
    ]
