# Generated by Django 6.0 on 2026-03-28 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0016_alter_insumos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoproducto',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date(2026, 3, 27)),
        ),
        migrations.AlterField(
            model_name='ingresoproducto2',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date(2026, 3, 27)),
        ),
    ]
