# Generated by Django 6.0 on 2026-03-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0017_alter_ingresoproducto_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoproducto2',
            name='salida',
            field=models.BooleanField(default=False),
        ),
    ]
