# Generated by Django 6.0 on 2026-03-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0018_ingresoproducto2_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoproducto2',
            name='salida',
            field=models.BooleanField(default=False, verbose_name='¿Es salida?'),
        ),
    ]
