# Generated by Django 6.0 on 2026-03-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0019_alter_ingresoproducto2_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoproducto2',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingresoproducto2',
            name='salida',
            field=models.IntegerField(default=0),
        ),
    ]
