# Generated by Django 4.2.16 on 2025-06-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0003_alter_venta_options_remove_venta_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
