# Generated by Django 4.2.16 on 2025-10-28 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0004_alter_venta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
