# Generated by Django 5.0.4 on 2024-08-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_mod',
            field=models.DateField(auto_now_add=True),
        ),
    ]
