# Generated by Django 4.2.15 on 2024-10-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_fecha_alter_user_fecha_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='conteo',
            field=models.IntegerField(default=0),
        ),
    ]
