# Generated by Django 5.0.4 on 2024-10-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_conteo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comision',
        ),
        migrations.RemoveField(
            model_name='user',
            name='conteo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salario',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ventas',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ventas_hoy',
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_mod',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='usuario',
            field=models.CharField(blank=True, default='Admin', max_length=250, null=True),
        ),
    ]
