# Generated by Django 5.0.4 on 2024-11-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='factura',
            field=models.TextField(blank=True, default='S/F', null=True),
        ),
    ]
