# Generated by Django 5.0.4 on 2024-11-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastos', '0002_gastos_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
