# Generated by Django 5.0.4 on 2024-11-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastos', '0003_gastos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
