# Generated by Django 4.2.16 on 2025-09-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastos', '0004_alter_gastos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='fecha_mod',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
